// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	backup "github.com/bluven/f-cloud/app/storage/api/internal/handler/backup"
	disk "github.com/bluven/f-cloud/app/storage/api/internal/handler/disk"
	health "github.com/bluven/f-cloud/app/storage/api/internal/handler/health"
	"github.com/bluven/f-cloud/app/storage/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CurrentUserRequiredMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/backups",
					Handler: backup.ListBackupsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/backups",
					Handler: backup.CreateDiskHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/backups/:id",
					Handler: backup.GetBackupHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/backups/:id",
					Handler: backup.UpdateBackupHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/backups/:id",
					Handler: backup.DeleteBackupHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CurrentUserRequiredMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/disks",
					Handler: disk.ListDisksHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/disks",
					Handler: disk.CreateDiskHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/disks/:id",
					Handler: disk.GetDiskHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/disks/:id",
					Handler: disk.DeleteDiskHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/disks/:id/extend",
					Handler: disk.ExtendDiskHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.HealthHandler(serverCtx),
			},
		},
	)
}
