// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/bluven/f-cloud/app/storage/model"
)

func newBackup(db *gorm.DB, opts ...gen.DOOption) backup {
	_backup := backup{}

	_backup.backupDo.UseDB(db, opts...)
	_backup.backupDo.UseModel(&model.Backup{})

	tableName := _backup.backupDo.TableName()
	_backup.ALL = field.NewAsterisk(tableName)
	_backup.ID = field.NewUint(tableName, "id")
	_backup.CreatedAt = field.NewTime(tableName, "created_at")
	_backup.UpdatedAt = field.NewTime(tableName, "updated_at")
	_backup.Name = field.NewString(tableName, "name")
	_backup.Schedule = field.NewString(tableName, "schedule")
	_backup.DiskID = field.NewUint(tableName, "disk_id")
	_backup.Disk = backupBelongsToDisk{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Disk", "model.Disk"),
	}

	_backup.fillFieldMap()

	return _backup
}

type backup struct {
	backupDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	Name      field.String
	Schedule  field.String
	DiskID    field.Uint
	Disk      backupBelongsToDisk

	fieldMap map[string]field.Expr
}

func (b backup) Table(newTableName string) *backup {
	b.backupDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b backup) As(alias string) *backup {
	b.backupDo.DO = *(b.backupDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *backup) updateTableName(table string) *backup {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewUint(table, "id")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")
	b.Name = field.NewString(table, "name")
	b.Schedule = field.NewString(table, "schedule")
	b.DiskID = field.NewUint(table, "disk_id")

	b.fillFieldMap()

	return b
}

func (b *backup) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *backup) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 7)
	b.fieldMap["id"] = b.ID
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
	b.fieldMap["name"] = b.Name
	b.fieldMap["schedule"] = b.Schedule
	b.fieldMap["disk_id"] = b.DiskID

}

func (b backup) clone(db *gorm.DB) backup {
	b.backupDo.ReplaceConnPool(db.Statement.ConnPool)
	b.Disk.db = db.Session(&gorm.Session{Initialized: true})
	b.Disk.db.Statement.ConnPool = db.Statement.ConnPool
	return b
}

func (b backup) replaceDB(db *gorm.DB) backup {
	b.backupDo.ReplaceDB(db)
	b.Disk.db = db.Session(&gorm.Session{})
	return b
}

type backupBelongsToDisk struct {
	db *gorm.DB

	field.RelationField
}

func (a backupBelongsToDisk) Where(conds ...field.Expr) *backupBelongsToDisk {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a backupBelongsToDisk) WithContext(ctx context.Context) *backupBelongsToDisk {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a backupBelongsToDisk) Session(session *gorm.Session) *backupBelongsToDisk {
	a.db = a.db.Session(session)
	return &a
}

func (a backupBelongsToDisk) Model(m *model.Backup) *backupBelongsToDiskTx {
	return &backupBelongsToDiskTx{a.db.Model(m).Association(a.Name())}
}

func (a backupBelongsToDisk) Unscoped() *backupBelongsToDisk {
	a.db = a.db.Unscoped()
	return &a
}

type backupBelongsToDiskTx struct{ tx *gorm.Association }

func (a backupBelongsToDiskTx) Find() (result *model.Disk, err error) {
	return result, a.tx.Find(&result)
}

func (a backupBelongsToDiskTx) Append(values ...*model.Disk) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a backupBelongsToDiskTx) Replace(values ...*model.Disk) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a backupBelongsToDiskTx) Delete(values ...*model.Disk) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a backupBelongsToDiskTx) Clear() error {
	return a.tx.Clear()
}

func (a backupBelongsToDiskTx) Count() int64 {
	return a.tx.Count()
}

func (a backupBelongsToDiskTx) Unscoped() *backupBelongsToDiskTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type backupDo struct{ gen.DO }

type IBackupDo interface {
	gen.SubQuery
	Debug() IBackupDo
	WithContext(ctx context.Context) IBackupDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBackupDo
	WriteDB() IBackupDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBackupDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBackupDo
	Not(conds ...gen.Condition) IBackupDo
	Or(conds ...gen.Condition) IBackupDo
	Select(conds ...field.Expr) IBackupDo
	Where(conds ...gen.Condition) IBackupDo
	Order(conds ...field.Expr) IBackupDo
	Distinct(cols ...field.Expr) IBackupDo
	Omit(cols ...field.Expr) IBackupDo
	Join(table schema.Tabler, on ...field.Expr) IBackupDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBackupDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBackupDo
	Group(cols ...field.Expr) IBackupDo
	Having(conds ...gen.Condition) IBackupDo
	Limit(limit int) IBackupDo
	Offset(offset int) IBackupDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBackupDo
	Unscoped() IBackupDo
	Create(values ...*model.Backup) error
	CreateInBatches(values []*model.Backup, batchSize int) error
	Save(values ...*model.Backup) error
	First() (*model.Backup, error)
	Take() (*model.Backup, error)
	Last() (*model.Backup, error)
	Find() ([]*model.Backup, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Backup, err error)
	FindInBatches(result *[]*model.Backup, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Backup) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBackupDo
	Assign(attrs ...field.AssignExpr) IBackupDo
	Joins(fields ...field.RelationField) IBackupDo
	Preload(fields ...field.RelationField) IBackupDo
	FirstOrInit() (*model.Backup, error)
	FirstOrCreate() (*model.Backup, error)
	FindByPage(offset int, limit int) (result []*model.Backup, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBackupDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetByID(id uint) (result model.Backup, err error)
	Exists(name string) (result bool, err error)
	SelectByName(name string) (result []model.Backup, err error)
}

// SELECT * FROM @@table WHERE id = @id
func (b backupDo) GetByID(id uint) (result model.Backup, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM backups WHERE id = ? ")

	var executeSQL *gorm.DB
	executeSQL = b.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// SELECT count(1) FROM @@table WHERE name = @name
func (b backupDo) Exists(name string) (result bool, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	generateSQL.WriteString("SELECT count(1) FROM backups WHERE name = ? ")

	var executeSQL *gorm.DB
	executeSQL = b.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// SELECT * FROM @@table WHERE name = '%@name'
func (b backupDo) SelectByName(name string) (result []model.Backup, err error) {
	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM backups WHERE name = '%@name' ")

	var executeSQL *gorm.DB
	executeSQL = b.UnderlyingDB().Raw(generateSQL.String()).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (b backupDo) Debug() IBackupDo {
	return b.withDO(b.DO.Debug())
}

func (b backupDo) WithContext(ctx context.Context) IBackupDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b backupDo) ReadDB() IBackupDo {
	return b.Clauses(dbresolver.Read)
}

func (b backupDo) WriteDB() IBackupDo {
	return b.Clauses(dbresolver.Write)
}

func (b backupDo) Session(config *gorm.Session) IBackupDo {
	return b.withDO(b.DO.Session(config))
}

func (b backupDo) Clauses(conds ...clause.Expression) IBackupDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b backupDo) Returning(value interface{}, columns ...string) IBackupDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b backupDo) Not(conds ...gen.Condition) IBackupDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b backupDo) Or(conds ...gen.Condition) IBackupDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b backupDo) Select(conds ...field.Expr) IBackupDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b backupDo) Where(conds ...gen.Condition) IBackupDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b backupDo) Order(conds ...field.Expr) IBackupDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b backupDo) Distinct(cols ...field.Expr) IBackupDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b backupDo) Omit(cols ...field.Expr) IBackupDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b backupDo) Join(table schema.Tabler, on ...field.Expr) IBackupDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b backupDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBackupDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b backupDo) RightJoin(table schema.Tabler, on ...field.Expr) IBackupDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b backupDo) Group(cols ...field.Expr) IBackupDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b backupDo) Having(conds ...gen.Condition) IBackupDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b backupDo) Limit(limit int) IBackupDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b backupDo) Offset(offset int) IBackupDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b backupDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBackupDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b backupDo) Unscoped() IBackupDo {
	return b.withDO(b.DO.Unscoped())
}

func (b backupDo) Create(values ...*model.Backup) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b backupDo) CreateInBatches(values []*model.Backup, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b backupDo) Save(values ...*model.Backup) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b backupDo) First() (*model.Backup, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Backup), nil
	}
}

func (b backupDo) Take() (*model.Backup, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Backup), nil
	}
}

func (b backupDo) Last() (*model.Backup, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Backup), nil
	}
}

func (b backupDo) Find() ([]*model.Backup, error) {
	result, err := b.DO.Find()
	return result.([]*model.Backup), err
}

func (b backupDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Backup, err error) {
	buf := make([]*model.Backup, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b backupDo) FindInBatches(result *[]*model.Backup, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b backupDo) Attrs(attrs ...field.AssignExpr) IBackupDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b backupDo) Assign(attrs ...field.AssignExpr) IBackupDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b backupDo) Joins(fields ...field.RelationField) IBackupDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b backupDo) Preload(fields ...field.RelationField) IBackupDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b backupDo) FirstOrInit() (*model.Backup, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Backup), nil
	}
}

func (b backupDo) FirstOrCreate() (*model.Backup, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Backup), nil
	}
}

func (b backupDo) FindByPage(offset int, limit int) (result []*model.Backup, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b backupDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b backupDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b backupDo) Delete(models ...*model.Backup) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *backupDo) withDO(do gen.Dao) *backupDo {
	b.DO = *do.(*gen.DO)
	return b
}
