// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/bluven/f-cloud/app/storage/model"
)

func newDisk(db *gorm.DB, opts ...gen.DOOption) disk {
	_disk := disk{}

	_disk.diskDo.UseDB(db, opts...)
	_disk.diskDo.UseModel(&model.Disk{})

	tableName := _disk.diskDo.TableName()
	_disk.ALL = field.NewAsterisk(tableName)
	_disk.ID = field.NewUint(tableName, "id")
	_disk.CreatedAt = field.NewTime(tableName, "created_at")
	_disk.UpdatedAt = field.NewTime(tableName, "updated_at")
	_disk.Name = field.NewString(tableName, "name")
	_disk.Size = field.NewUint(tableName, "size")
	_disk.Type = field.NewString(tableName, "type")
	_disk.InstanceID = field.NewUint(tableName, "instance_id")

	_disk.fillFieldMap()

	return _disk
}

type disk struct {
	diskDo

	ALL        field.Asterisk
	ID         field.Uint
	CreatedAt  field.Time
	UpdatedAt  field.Time
	Name       field.String
	Size       field.Uint
	Type       field.String
	InstanceID field.Uint

	fieldMap map[string]field.Expr
}

func (d disk) Table(newTableName string) *disk {
	d.diskDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d disk) As(alias string) *disk {
	d.diskDo.DO = *(d.diskDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *disk) updateTableName(table string) *disk {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint(table, "id")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")
	d.Name = field.NewString(table, "name")
	d.Size = field.NewUint(table, "size")
	d.Type = field.NewString(table, "type")
	d.InstanceID = field.NewUint(table, "instance_id")

	d.fillFieldMap()

	return d
}

func (d *disk) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *disk) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 7)
	d.fieldMap["id"] = d.ID
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
	d.fieldMap["name"] = d.Name
	d.fieldMap["size"] = d.Size
	d.fieldMap["type"] = d.Type
	d.fieldMap["instance_id"] = d.InstanceID
}

func (d disk) clone(db *gorm.DB) disk {
	d.diskDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d disk) replaceDB(db *gorm.DB) disk {
	d.diskDo.ReplaceDB(db)
	return d
}

type diskDo struct{ gen.DO }

type IDiskDo interface {
	gen.SubQuery
	Debug() IDiskDo
	WithContext(ctx context.Context) IDiskDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDiskDo
	WriteDB() IDiskDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDiskDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDiskDo
	Not(conds ...gen.Condition) IDiskDo
	Or(conds ...gen.Condition) IDiskDo
	Select(conds ...field.Expr) IDiskDo
	Where(conds ...gen.Condition) IDiskDo
	Order(conds ...field.Expr) IDiskDo
	Distinct(cols ...field.Expr) IDiskDo
	Omit(cols ...field.Expr) IDiskDo
	Join(table schema.Tabler, on ...field.Expr) IDiskDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDiskDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDiskDo
	Group(cols ...field.Expr) IDiskDo
	Having(conds ...gen.Condition) IDiskDo
	Limit(limit int) IDiskDo
	Offset(offset int) IDiskDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDiskDo
	Unscoped() IDiskDo
	Create(values ...*model.Disk) error
	CreateInBatches(values []*model.Disk, batchSize int) error
	Save(values ...*model.Disk) error
	First() (*model.Disk, error)
	Take() (*model.Disk, error)
	Last() (*model.Disk, error)
	Find() ([]*model.Disk, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Disk, err error)
	FindInBatches(result *[]*model.Disk, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Disk) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDiskDo
	Assign(attrs ...field.AssignExpr) IDiskDo
	Joins(fields ...field.RelationField) IDiskDo
	Preload(fields ...field.RelationField) IDiskDo
	FirstOrInit() (*model.Disk, error)
	FirstOrCreate() (*model.Disk, error)
	FindByPage(offset int, limit int) (result []*model.Disk, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDiskDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetByID(id uint) (result model.Disk, err error)
	Exists(name string) (result bool, err error)
	SelectByName(name string) (result []model.Disk, err error)
	UpdateInstanceID(id uint, instanceID *uint) (rowsAffected int64, err error)
}

// SELECT * FROM @@table WHERE id = @id
func (d diskDo) GetByID(id uint) (result model.Disk, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM disks WHERE id = ? ")

	var executeSQL *gorm.DB
	executeSQL = d.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// SELECT count(1) FROM @@table WHERE name = @name
func (d diskDo) Exists(name string) (result bool, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	generateSQL.WriteString("SELECT count(1) FROM disks WHERE name = ? ")

	var executeSQL *gorm.DB
	executeSQL = d.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// SELECT * FROM @@table WHERE name = '%@name'
func (d diskDo) SelectByName(name string) (result []model.Disk, err error) {
	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM disks WHERE name = '%@name' ")

	var executeSQL *gorm.DB
	executeSQL = d.UnderlyingDB().Raw(generateSQL.String()).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// UPDATE @@table SET instance_id = @instanceID WHERE id = @id
func (d diskDo) UpdateInstanceID(id uint, instanceID *uint) (rowsAffected int64, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, instanceID)
	params = append(params, id)
	generateSQL.WriteString("UPDATE disks SET instance_id = ? WHERE id = ? ")

	var executeSQL *gorm.DB
	executeSQL = d.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	rowsAffected = executeSQL.RowsAffected
	err = executeSQL.Error

	return
}

func (d diskDo) Debug() IDiskDo {
	return d.withDO(d.DO.Debug())
}

func (d diskDo) WithContext(ctx context.Context) IDiskDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d diskDo) ReadDB() IDiskDo {
	return d.Clauses(dbresolver.Read)
}

func (d diskDo) WriteDB() IDiskDo {
	return d.Clauses(dbresolver.Write)
}

func (d diskDo) Session(config *gorm.Session) IDiskDo {
	return d.withDO(d.DO.Session(config))
}

func (d diskDo) Clauses(conds ...clause.Expression) IDiskDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d diskDo) Returning(value interface{}, columns ...string) IDiskDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d diskDo) Not(conds ...gen.Condition) IDiskDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d diskDo) Or(conds ...gen.Condition) IDiskDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d diskDo) Select(conds ...field.Expr) IDiskDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d diskDo) Where(conds ...gen.Condition) IDiskDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d diskDo) Order(conds ...field.Expr) IDiskDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d diskDo) Distinct(cols ...field.Expr) IDiskDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d diskDo) Omit(cols ...field.Expr) IDiskDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d diskDo) Join(table schema.Tabler, on ...field.Expr) IDiskDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d diskDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDiskDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d diskDo) RightJoin(table schema.Tabler, on ...field.Expr) IDiskDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d diskDo) Group(cols ...field.Expr) IDiskDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d diskDo) Having(conds ...gen.Condition) IDiskDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d diskDo) Limit(limit int) IDiskDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d diskDo) Offset(offset int) IDiskDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d diskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDiskDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d diskDo) Unscoped() IDiskDo {
	return d.withDO(d.DO.Unscoped())
}

func (d diskDo) Create(values ...*model.Disk) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d diskDo) CreateInBatches(values []*model.Disk, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d diskDo) Save(values ...*model.Disk) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d diskDo) First() (*model.Disk, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Disk), nil
	}
}

func (d diskDo) Take() (*model.Disk, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Disk), nil
	}
}

func (d diskDo) Last() (*model.Disk, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Disk), nil
	}
}

func (d diskDo) Find() ([]*model.Disk, error) {
	result, err := d.DO.Find()
	return result.([]*model.Disk), err
}

func (d diskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Disk, err error) {
	buf := make([]*model.Disk, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d diskDo) FindInBatches(result *[]*model.Disk, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d diskDo) Attrs(attrs ...field.AssignExpr) IDiskDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d diskDo) Assign(attrs ...field.AssignExpr) IDiskDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d diskDo) Joins(fields ...field.RelationField) IDiskDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d diskDo) Preload(fields ...field.RelationField) IDiskDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d diskDo) FirstOrInit() (*model.Disk, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Disk), nil
	}
}

func (d diskDo) FirstOrCreate() (*model.Disk, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Disk), nil
	}
}

func (d diskDo) FindByPage(offset int, limit int) (result []*model.Disk, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d diskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d diskDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d diskDo) Delete(models ...*model.Disk) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *diskDo) withDO(do gen.Dao) *diskDo {
	d.DO = *do.(*gen.DO)
	return d
}
