// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: storage.proto

package storage

import (
	"context"

	"github.com/bluven/f-cloud/app/storage/rpc/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	MountDiskRequest    = proto.MountDiskRequest
	MountDiskResponse   = proto.MountDiskResponse
	UnmountDiskRequest  = proto.UnmountDiskRequest
	UnmountDiskResponse = proto.UnmountDiskResponse

	Storage interface {
		MountDisk(ctx context.Context, in *MountDiskRequest, opts ...grpc.CallOption) (*MountDiskResponse, error)
		UnmountDisk(ctx context.Context, in *UnmountDiskRequest, opts ...grpc.CallOption) (*UnmountDiskResponse, error)
	}

	defaultStorage struct {
		cli zrpc.Client
	}
)

func NewStorage(cli zrpc.Client) Storage {
	return &defaultStorage{
		cli: cli,
	}
}

func (m *defaultStorage) MountDisk(ctx context.Context, in *MountDiskRequest, opts ...grpc.CallOption) (*MountDiskResponse, error) {
	client := proto.NewStorageClient(m.cli.Conn())
	return client.MountDisk(ctx, in, opts...)
}

func (m *defaultStorage) UnmountDisk(ctx context.Context, in *UnmountDiskRequest, opts ...grpc.CallOption) (*UnmountDiskResponse, error) {
	client := proto.NewStorageClient(m.cli.Conn())
	return client.UnmountDisk(ctx, in, opts...)
}
