// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/bluven/f-cloud/app/network/model"
)

func newLoadBalancer(db *gorm.DB, opts ...gen.DOOption) loadBalancer {
	_loadBalancer := loadBalancer{}

	_loadBalancer.loadBalancerDo.UseDB(db, opts...)
	_loadBalancer.loadBalancerDo.UseModel(&model.LoadBalancer{})

	tableName := _loadBalancer.loadBalancerDo.TableName()
	_loadBalancer.ALL = field.NewAsterisk(tableName)
	_loadBalancer.ID = field.NewUint(tableName, "id")
	_loadBalancer.CreatedAt = field.NewTime(tableName, "created_at")
	_loadBalancer.UpdatedAt = field.NewTime(tableName, "updated_at")
	_loadBalancer.Name = field.NewString(tableName, "name")
	_loadBalancer.NetworkID = field.NewUint(tableName, "network_id")
	_loadBalancer.Algorithm = field.NewString(tableName, "algorithm")
	_loadBalancer.Network = loadBalancerBelongsToNetwork{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Network", "model.Network"),
	}

	_loadBalancer.fillFieldMap()

	return _loadBalancer
}

type loadBalancer struct {
	loadBalancerDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	Name      field.String
	NetworkID field.Uint
	Algorithm field.String
	Network   loadBalancerBelongsToNetwork

	fieldMap map[string]field.Expr
}

func (l loadBalancer) Table(newTableName string) *loadBalancer {
	l.loadBalancerDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l loadBalancer) As(alias string) *loadBalancer {
	l.loadBalancerDo.DO = *(l.loadBalancerDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *loadBalancer) updateTableName(table string) *loadBalancer {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewUint(table, "id")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")
	l.Name = field.NewString(table, "name")
	l.NetworkID = field.NewUint(table, "network_id")
	l.Algorithm = field.NewString(table, "algorithm")

	l.fillFieldMap()

	return l
}

func (l *loadBalancer) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *loadBalancer) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 7)
	l.fieldMap["id"] = l.ID
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
	l.fieldMap["name"] = l.Name
	l.fieldMap["network_id"] = l.NetworkID
	l.fieldMap["algorithm"] = l.Algorithm

}

func (l loadBalancer) clone(db *gorm.DB) loadBalancer {
	l.loadBalancerDo.ReplaceConnPool(db.Statement.ConnPool)
	l.Network.db = db.Session(&gorm.Session{Initialized: true})
	l.Network.db.Statement.ConnPool = db.Statement.ConnPool
	return l
}

func (l loadBalancer) replaceDB(db *gorm.DB) loadBalancer {
	l.loadBalancerDo.ReplaceDB(db)
	l.Network.db = db.Session(&gorm.Session{})
	return l
}

type loadBalancerBelongsToNetwork struct {
	db *gorm.DB

	field.RelationField
}

func (a loadBalancerBelongsToNetwork) Where(conds ...field.Expr) *loadBalancerBelongsToNetwork {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a loadBalancerBelongsToNetwork) WithContext(ctx context.Context) *loadBalancerBelongsToNetwork {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a loadBalancerBelongsToNetwork) Session(session *gorm.Session) *loadBalancerBelongsToNetwork {
	a.db = a.db.Session(session)
	return &a
}

func (a loadBalancerBelongsToNetwork) Model(m *model.LoadBalancer) *loadBalancerBelongsToNetworkTx {
	return &loadBalancerBelongsToNetworkTx{a.db.Model(m).Association(a.Name())}
}

func (a loadBalancerBelongsToNetwork) Unscoped() *loadBalancerBelongsToNetwork {
	a.db = a.db.Unscoped()
	return &a
}

type loadBalancerBelongsToNetworkTx struct{ tx *gorm.Association }

func (a loadBalancerBelongsToNetworkTx) Find() (result *model.Network, err error) {
	return result, a.tx.Find(&result)
}

func (a loadBalancerBelongsToNetworkTx) Append(values ...*model.Network) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a loadBalancerBelongsToNetworkTx) Replace(values ...*model.Network) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a loadBalancerBelongsToNetworkTx) Delete(values ...*model.Network) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a loadBalancerBelongsToNetworkTx) Clear() error {
	return a.tx.Clear()
}

func (a loadBalancerBelongsToNetworkTx) Count() int64 {
	return a.tx.Count()
}

func (a loadBalancerBelongsToNetworkTx) Unscoped() *loadBalancerBelongsToNetworkTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type loadBalancerDo struct{ gen.DO }

type ILoadBalancerDo interface {
	gen.SubQuery
	Debug() ILoadBalancerDo
	WithContext(ctx context.Context) ILoadBalancerDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILoadBalancerDo
	WriteDB() ILoadBalancerDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILoadBalancerDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILoadBalancerDo
	Not(conds ...gen.Condition) ILoadBalancerDo
	Or(conds ...gen.Condition) ILoadBalancerDo
	Select(conds ...field.Expr) ILoadBalancerDo
	Where(conds ...gen.Condition) ILoadBalancerDo
	Order(conds ...field.Expr) ILoadBalancerDo
	Distinct(cols ...field.Expr) ILoadBalancerDo
	Omit(cols ...field.Expr) ILoadBalancerDo
	Join(table schema.Tabler, on ...field.Expr) ILoadBalancerDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILoadBalancerDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILoadBalancerDo
	Group(cols ...field.Expr) ILoadBalancerDo
	Having(conds ...gen.Condition) ILoadBalancerDo
	Limit(limit int) ILoadBalancerDo
	Offset(offset int) ILoadBalancerDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILoadBalancerDo
	Unscoped() ILoadBalancerDo
	Create(values ...*model.LoadBalancer) error
	CreateInBatches(values []*model.LoadBalancer, batchSize int) error
	Save(values ...*model.LoadBalancer) error
	First() (*model.LoadBalancer, error)
	Take() (*model.LoadBalancer, error)
	Last() (*model.LoadBalancer, error)
	Find() ([]*model.LoadBalancer, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LoadBalancer, err error)
	FindInBatches(result *[]*model.LoadBalancer, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LoadBalancer) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILoadBalancerDo
	Assign(attrs ...field.AssignExpr) ILoadBalancerDo
	Joins(fields ...field.RelationField) ILoadBalancerDo
	Preload(fields ...field.RelationField) ILoadBalancerDo
	FirstOrInit() (*model.LoadBalancer, error)
	FirstOrCreate() (*model.LoadBalancer, error)
	FindByPage(offset int, limit int) (result []*model.LoadBalancer, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILoadBalancerDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetByID(id uint) (result model.LoadBalancer, err error)
	Exists(name string) (result bool, err error)
	SelectByName(name string) (result []model.LoadBalancer, err error)
}

// SELECT * FROM @@table WHERE id = @id
func (l loadBalancerDo) GetByID(id uint) (result model.LoadBalancer, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM load_balancers WHERE id = ? ")

	var executeSQL *gorm.DB
	executeSQL = l.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// SELECT count(1) FROM @@table WHERE name = @name
func (l loadBalancerDo) Exists(name string) (result bool, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	generateSQL.WriteString("SELECT count(1) FROM load_balancers WHERE name = ? ")

	var executeSQL *gorm.DB
	executeSQL = l.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// SELECT * FROM @@table WHERE name = '%@name'
func (l loadBalancerDo) SelectByName(name string) (result []model.LoadBalancer, err error) {
	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM load_balancers WHERE name = '%@name' ")

	var executeSQL *gorm.DB
	executeSQL = l.UnderlyingDB().Raw(generateSQL.String()).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (l loadBalancerDo) Debug() ILoadBalancerDo {
	return l.withDO(l.DO.Debug())
}

func (l loadBalancerDo) WithContext(ctx context.Context) ILoadBalancerDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l loadBalancerDo) ReadDB() ILoadBalancerDo {
	return l.Clauses(dbresolver.Read)
}

func (l loadBalancerDo) WriteDB() ILoadBalancerDo {
	return l.Clauses(dbresolver.Write)
}

func (l loadBalancerDo) Session(config *gorm.Session) ILoadBalancerDo {
	return l.withDO(l.DO.Session(config))
}

func (l loadBalancerDo) Clauses(conds ...clause.Expression) ILoadBalancerDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l loadBalancerDo) Returning(value interface{}, columns ...string) ILoadBalancerDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l loadBalancerDo) Not(conds ...gen.Condition) ILoadBalancerDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l loadBalancerDo) Or(conds ...gen.Condition) ILoadBalancerDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l loadBalancerDo) Select(conds ...field.Expr) ILoadBalancerDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l loadBalancerDo) Where(conds ...gen.Condition) ILoadBalancerDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l loadBalancerDo) Order(conds ...field.Expr) ILoadBalancerDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l loadBalancerDo) Distinct(cols ...field.Expr) ILoadBalancerDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l loadBalancerDo) Omit(cols ...field.Expr) ILoadBalancerDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l loadBalancerDo) Join(table schema.Tabler, on ...field.Expr) ILoadBalancerDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l loadBalancerDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILoadBalancerDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l loadBalancerDo) RightJoin(table schema.Tabler, on ...field.Expr) ILoadBalancerDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l loadBalancerDo) Group(cols ...field.Expr) ILoadBalancerDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l loadBalancerDo) Having(conds ...gen.Condition) ILoadBalancerDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l loadBalancerDo) Limit(limit int) ILoadBalancerDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l loadBalancerDo) Offset(offset int) ILoadBalancerDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l loadBalancerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILoadBalancerDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l loadBalancerDo) Unscoped() ILoadBalancerDo {
	return l.withDO(l.DO.Unscoped())
}

func (l loadBalancerDo) Create(values ...*model.LoadBalancer) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l loadBalancerDo) CreateInBatches(values []*model.LoadBalancer, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l loadBalancerDo) Save(values ...*model.LoadBalancer) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l loadBalancerDo) First() (*model.LoadBalancer, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoadBalancer), nil
	}
}

func (l loadBalancerDo) Take() (*model.LoadBalancer, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoadBalancer), nil
	}
}

func (l loadBalancerDo) Last() (*model.LoadBalancer, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoadBalancer), nil
	}
}

func (l loadBalancerDo) Find() ([]*model.LoadBalancer, error) {
	result, err := l.DO.Find()
	return result.([]*model.LoadBalancer), err
}

func (l loadBalancerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LoadBalancer, err error) {
	buf := make([]*model.LoadBalancer, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l loadBalancerDo) FindInBatches(result *[]*model.LoadBalancer, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l loadBalancerDo) Attrs(attrs ...field.AssignExpr) ILoadBalancerDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l loadBalancerDo) Assign(attrs ...field.AssignExpr) ILoadBalancerDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l loadBalancerDo) Joins(fields ...field.RelationField) ILoadBalancerDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l loadBalancerDo) Preload(fields ...field.RelationField) ILoadBalancerDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l loadBalancerDo) FirstOrInit() (*model.LoadBalancer, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoadBalancer), nil
	}
}

func (l loadBalancerDo) FirstOrCreate() (*model.LoadBalancer, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoadBalancer), nil
	}
}

func (l loadBalancerDo) FindByPage(offset int, limit int) (result []*model.LoadBalancer, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l loadBalancerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l loadBalancerDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l loadBalancerDo) Delete(models ...*model.LoadBalancer) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *loadBalancerDo) withDO(do gen.Dao) *loadBalancerDo {
	l.DO = *do.(*gen.DO)
	return l
}
