// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/bluven/f-cloud/app/network/model"
)

func newNetwork(db *gorm.DB, opts ...gen.DOOption) network {
	_network := network{}

	_network.networkDo.UseDB(db, opts...)
	_network.networkDo.UseModel(&model.Network{})

	tableName := _network.networkDo.TableName()
	_network.ALL = field.NewAsterisk(tableName)
	_network.ID = field.NewUint(tableName, "id")
	_network.CreatedAt = field.NewTime(tableName, "created_at")
	_network.UpdatedAt = field.NewTime(tableName, "updated_at")
	_network.Name = field.NewString(tableName, "name")
	_network.IPv4Addr = field.NewString(tableName, "ipv4_addr")
	_network.Bandwidth = field.NewUint(tableName, "bandwidth")
	_network.Traffic = field.NewUint(tableName, "traffic")
	_network.InstanceID = field.NewUint(tableName, "instance_id")

	_network.fillFieldMap()

	return _network
}

type network struct {
	networkDo

	ALL        field.Asterisk
	ID         field.Uint
	CreatedAt  field.Time
	UpdatedAt  field.Time
	Name       field.String
	IPv4Addr   field.String
	Bandwidth  field.Uint
	Traffic    field.Uint
	InstanceID field.Uint

	fieldMap map[string]field.Expr
}

func (n network) Table(newTableName string) *network {
	n.networkDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n network) As(alias string) *network {
	n.networkDo.DO = *(n.networkDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *network) updateTableName(table string) *network {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewUint(table, "id")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")
	n.Name = field.NewString(table, "name")
	n.IPv4Addr = field.NewString(table, "ipv4_addr")
	n.Bandwidth = field.NewUint(table, "bandwidth")
	n.Traffic = field.NewUint(table, "traffic")
	n.InstanceID = field.NewUint(table, "instance_id")

	n.fillFieldMap()

	return n
}

func (n *network) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *network) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 8)
	n.fieldMap["id"] = n.ID
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
	n.fieldMap["name"] = n.Name
	n.fieldMap["ipv4_addr"] = n.IPv4Addr
	n.fieldMap["bandwidth"] = n.Bandwidth
	n.fieldMap["traffic"] = n.Traffic
	n.fieldMap["instance_id"] = n.InstanceID
}

func (n network) clone(db *gorm.DB) network {
	n.networkDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n network) replaceDB(db *gorm.DB) network {
	n.networkDo.ReplaceDB(db)
	return n
}

type networkDo struct{ gen.DO }

type INetworkDo interface {
	gen.SubQuery
	Debug() INetworkDo
	WithContext(ctx context.Context) INetworkDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INetworkDo
	WriteDB() INetworkDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INetworkDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INetworkDo
	Not(conds ...gen.Condition) INetworkDo
	Or(conds ...gen.Condition) INetworkDo
	Select(conds ...field.Expr) INetworkDo
	Where(conds ...gen.Condition) INetworkDo
	Order(conds ...field.Expr) INetworkDo
	Distinct(cols ...field.Expr) INetworkDo
	Omit(cols ...field.Expr) INetworkDo
	Join(table schema.Tabler, on ...field.Expr) INetworkDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INetworkDo
	RightJoin(table schema.Tabler, on ...field.Expr) INetworkDo
	Group(cols ...field.Expr) INetworkDo
	Having(conds ...gen.Condition) INetworkDo
	Limit(limit int) INetworkDo
	Offset(offset int) INetworkDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INetworkDo
	Unscoped() INetworkDo
	Create(values ...*model.Network) error
	CreateInBatches(values []*model.Network, batchSize int) error
	Save(values ...*model.Network) error
	First() (*model.Network, error)
	Take() (*model.Network, error)
	Last() (*model.Network, error)
	Find() ([]*model.Network, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Network, err error)
	FindInBatches(result *[]*model.Network, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Network) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INetworkDo
	Assign(attrs ...field.AssignExpr) INetworkDo
	Joins(fields ...field.RelationField) INetworkDo
	Preload(fields ...field.RelationField) INetworkDo
	FirstOrInit() (*model.Network, error)
	FirstOrCreate() (*model.Network, error)
	FindByPage(offset int, limit int) (result []*model.Network, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INetworkDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetByID(id uint) (result model.Network, err error)
	Exists(name string) (result bool, err error)
	SelectByName(name string) (result []model.Network, err error)
	UpdateInstanceID(id uint, instanceID *uint) (rowsAffected int64, err error)
}

// SELECT * FROM @@table WHERE id = @id
func (n networkDo) GetByID(id uint) (result model.Network, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM networks WHERE id = ? ")

	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// SELECT count(1) FROM @@table WHERE name = @name
func (n networkDo) Exists(name string) (result bool, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	generateSQL.WriteString("SELECT count(1) FROM networks WHERE name = ? ")

	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// SELECT * FROM @@table WHERE name = '%@name'
func (n networkDo) SelectByName(name string) (result []model.Network, err error) {
	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM networks WHERE name = '%@name' ")

	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Raw(generateSQL.String()).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// UPDATE @@table SET instance_id = @instanceID WHERE id = @id
func (n networkDo) UpdateInstanceID(id uint, instanceID *uint) (rowsAffected int64, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, instanceID)
	params = append(params, id)
	generateSQL.WriteString("UPDATE networks SET instance_id = ? WHERE id = ? ")

	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	rowsAffected = executeSQL.RowsAffected
	err = executeSQL.Error

	return
}

func (n networkDo) Debug() INetworkDo {
	return n.withDO(n.DO.Debug())
}

func (n networkDo) WithContext(ctx context.Context) INetworkDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n networkDo) ReadDB() INetworkDo {
	return n.Clauses(dbresolver.Read)
}

func (n networkDo) WriteDB() INetworkDo {
	return n.Clauses(dbresolver.Write)
}

func (n networkDo) Session(config *gorm.Session) INetworkDo {
	return n.withDO(n.DO.Session(config))
}

func (n networkDo) Clauses(conds ...clause.Expression) INetworkDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n networkDo) Returning(value interface{}, columns ...string) INetworkDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n networkDo) Not(conds ...gen.Condition) INetworkDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n networkDo) Or(conds ...gen.Condition) INetworkDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n networkDo) Select(conds ...field.Expr) INetworkDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n networkDo) Where(conds ...gen.Condition) INetworkDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n networkDo) Order(conds ...field.Expr) INetworkDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n networkDo) Distinct(cols ...field.Expr) INetworkDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n networkDo) Omit(cols ...field.Expr) INetworkDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n networkDo) Join(table schema.Tabler, on ...field.Expr) INetworkDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n networkDo) LeftJoin(table schema.Tabler, on ...field.Expr) INetworkDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n networkDo) RightJoin(table schema.Tabler, on ...field.Expr) INetworkDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n networkDo) Group(cols ...field.Expr) INetworkDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n networkDo) Having(conds ...gen.Condition) INetworkDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n networkDo) Limit(limit int) INetworkDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n networkDo) Offset(offset int) INetworkDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n networkDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INetworkDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n networkDo) Unscoped() INetworkDo {
	return n.withDO(n.DO.Unscoped())
}

func (n networkDo) Create(values ...*model.Network) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n networkDo) CreateInBatches(values []*model.Network, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n networkDo) Save(values ...*model.Network) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n networkDo) First() (*model.Network, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Network), nil
	}
}

func (n networkDo) Take() (*model.Network, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Network), nil
	}
}

func (n networkDo) Last() (*model.Network, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Network), nil
	}
}

func (n networkDo) Find() ([]*model.Network, error) {
	result, err := n.DO.Find()
	return result.([]*model.Network), err
}

func (n networkDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Network, err error) {
	buf := make([]*model.Network, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n networkDo) FindInBatches(result *[]*model.Network, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n networkDo) Attrs(attrs ...field.AssignExpr) INetworkDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n networkDo) Assign(attrs ...field.AssignExpr) INetworkDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n networkDo) Joins(fields ...field.RelationField) INetworkDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n networkDo) Preload(fields ...field.RelationField) INetworkDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n networkDo) FirstOrInit() (*model.Network, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Network), nil
	}
}

func (n networkDo) FirstOrCreate() (*model.Network, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Network), nil
	}
}

func (n networkDo) FindByPage(offset int, limit int) (result []*model.Network, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n networkDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n networkDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n networkDo) Delete(models ...*model.Network) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *networkDo) withDO(do gen.Dao) *networkDo {
	n.DO = *do.(*gen.DO)
	return n
}
