// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	loadbalancer "github.com/bluven/f-cloud/app/network/api/internal/handler/loadbalancer"
	network "github.com/bluven/f-cloud/app/network/api/internal/handler/network"
	"github.com/bluven/f-cloud/app/network/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CurrentUserRequiredMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/loadbalancers",
					Handler: loadbalancer.ListLoadBalancersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/loadbalancers",
					Handler: loadbalancer.CreateLoadBalancerHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/loadbalancers/:id",
					Handler: loadbalancer.GetLoadBalancerHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/loadbalancers/:id",
					Handler: loadbalancer.UpdateLoadBalancerHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/loadbalancers/:id",
					Handler: loadbalancer.DeleteLoadBalancerHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CurrentUserRequiredMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/networks",
					Handler: network.ListNetworksHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/networks",
					Handler: network.CreateNetworkHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/networks/:id",
					Handler: network.GetNetworkHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/networks/:id",
					Handler: network.UpdateNetworkHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/networks/:id",
					Handler: network.DeleteNetworkHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
