// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type CreateRequest struct {
	Name     string `json:"name" validate:"required,username"`
	Password string `json:"password" validate:"required,min=6,max=32"`
	Email    string `json:"email" validate:"required,email"`
	Mobile   string `json:"mobile" validate:"required"`
	IsAdmin  bool   `json:"isAdmin"`
}

type EmptyRequest struct {
}

type EmptyResponse struct {
}

type GetRequest struct {
	ID uint `path:"id"`
}

type LoginRequest struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type TokenResponse struct {
	Token        string `json:"token"`
	ExpireAt     int64  `json:"expireAt"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UpdatePasswordRequest struct {
	ID       uint   `path:"id"`
	Password string `json:"password" validate:"required,min=6,max=32"`
}

type UpdateRequest struct {
	ID      uint   `path:"id"`
	Email   string `json:"email" validate:"required,email"`
	Mobile  string `json:"mobile" validate:"required"`
	IsAdmin bool   `json:"isAdmin"`
}

type User struct {
	ID        uint   `json:"id"`
	Name      string `json:"name"`
	Mobile    string `json:"mobile"`
	Email     string `json:"email"`
	IsAdmin   bool   `json:"isAdmin"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}
