// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	"github.com/bluven/f-cloud/app/host/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminRequiredMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/hosts",
					Handler: CreateHostHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/hosts/",
					Handler: ListHostsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/hosts/:id",
					Handler: GetHostHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/hosts/:id",
					Handler: UpdateHostHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/hosts/:id/:operation",
					Handler: OperateHostHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
