// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type CreateLoadBalancerRequest struct {
	Name      string `json:"name" validate:"required,min=2,max=50"`
	NetworkID *uint  `json:"networkID,optional"`
	Algorithm string `json:"algorithm" validate:"required,oneof=roundrobin leastconn weighted leastresp iphash"`
}

type CreateNetworkRequest struct {
	Name      string `json:"name" validate:"required,min=2,max=50"`
	IPv4Addr  string `json:"ipv4Addr" validate:"required,ipv4"`
	Bandwidth uint   `json:"bandwidth" validate:"required,min=1,max=1000"`
	Traffic   uint   `json:"traffic" validate:"required,min=50,max=10000"`
}

type DeleteRequest struct {
	ID uint `path:"id"`
}

type EmptyRequest struct {
}

type EmptyResponse struct {
}

type GetRequest struct {
	ID uint `path:"id"`
}

type ListLoadBalancerRequest struct {
	Name     string `form:"name,optional"`
	Page     uint   `form:"page,default=1" validate:"min=1"`
	PageSize uint   `form:"pageSize,default=10" validate:"oneof=10 20 30 40 50"`
}

type ListLoadBalancerResponse struct {
	Items       []LoadBalancer `json:"networks"`
	TotalRecord uint           `json:"total"`
	TotalPage   uint           `json:"totalPage"`
	Page        uint           `json:"page"`
	PageSize    uint           `json:"pageSize"`
}

type ListNetworkRequest struct {
	Name     string `form:"name,optional"`
	Page     uint   `form:"page,default=1" validate:"min=1"`
	PageSize uint   `form:"pageSize,default=10" validate:"oneof=10 20 30 40 50"`
}

type ListNetworkResponse struct {
	Items       []Network `json:"networks"`
	TotalRecord uint      `json:"total"`
	TotalPage   uint      `json:"totalPage"`
	Page        uint      `json:"page"`
	PageSize    uint      `json:"pageSize"`
}

type LoadBalancer struct {
	ID        uint     `json:"id"`
	Name      string   `json:"name"`
	NetworkID *uint    `json:"networkID"`
	Network   *Network `json:"network"`
	Algorithm string   `json:"algorithm"`
	CreatedAt int64    `json:"createdAt"`
	UpdatedAt int64    `json:"updatedAt"`
}

type Network struct {
	ID         uint   `json:"id"`
	Name       string `json:"name"`
	IPv4Addr   string `json:"ipv4Addr"`
	Bandwidth  uint   `json:"bandwidth"`
	Traffic    uint   `json:"traffic"`
	InstanceID *uint  `json:"instanceID"`
	CreatedAt  int64  `json:"createdAt"`
	UpdatedAt  int64  `json:"updatedAt"`
}

type UpdateLoadBalancerRequest struct {
	ID        uint   `path:"id"`
	NetworkID *uint  `json:"networkID,optional"`
	Algorithm string `json:"algorithm" validate:"required,oneof=roundrobin leastconn weighted leastresp iphash"`
}

type UpdateNetworkRequest struct {
	ID        uint   `path:"id"`
	IPv4Addr  string `json:"ipv4Addr" validate:"required,ipv4"`
	Bandwidth uint   `json:"bandwidth" validate:"required,min=1,max=1000"`
	Traffic   uint   `json:"traffic" validate:"required,min=50,max=10000"`
}
