// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type Backup struct {
	ID        uint   `json:"id"`
	Name      string `json:"name"`
	Schedule  string `json:"schedule"`
	DiskID    *uint  `json:"diskID,omitempty"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type CreateBackupRequest struct {
	Name     string `json:"name" validate:"required,min=2,max=50"`
	Schedule string `json:"schedule" validate:"required"`
	DiskID   *uint  `json:"diskID,optional,omitempty"`
}

type CreateDiskRequest struct {
	Name string `json:"name" validate:"required,min=2,max=50"`
	Size uint   `json:"size" validate:"required,min=1,max=10000"`
	Type string `json:"type" validate:"required,oneof=hard ssd"`
}

type DeleteRequest struct {
	ID uint `path:"id"`
}

type Disk struct {
	ID        uint   `json:"id"`
	Name      string `json:"name"`
	Size      uint   `json:"size"`
	Type      string `json:"type"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type EmptyRequest struct {
}

type EmptyResponse struct {
}

type ExtendDiskRequest struct {
	ID   uint `path:"id"`
	Size uint `json:"size" validate:"required,min=1,max=10000"`
}

type GetRequest struct {
	ID uint `path:"id"`
}

type ListBackupRequest struct {
	DiskID uint `path:"diskID"`
}

type ListBackupResponse struct {
	Items []Backup `json:"backups"`
}

type ListDiskRequest struct {
	Name     string `form:"name,optional"`
	Page     uint   `form:"page,default=1" validate:"min=1"`
	PageSize uint   `form:"pageSize,default=10" validate:"oneof=10 20 30 40 50"`
}

type ListDiskResponse struct {
	Items       []Disk `json:"disks"`
	TotalRecord uint   `json:"total"`
	TotalPage   uint   `json:"totalPage"`
	Page        uint   `json:"page"`
	PageSize    uint   `json:"pageSize"`
}

type UpdateBackupRequest struct {
	ID       uint   `path:"id"`
	Schedule string `json:"schedule" validate:"required"`
}
