// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	instance "github.com/bluven/f-cloud/app/instance/api/internal/handler/instance"
	"github.com/bluven/f-cloud/app/instance/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CurrentUserRequired},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/instances",
					Handler: instance.ListInstancesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/instances",
					Handler: instance.CreateInstanceHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/instances/:id",
					Handler: instance.GetInstanceHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/instances/:id",
					Handler: instance.DeleteInstanceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/instances/:id/:operation",
					Handler: instance.OperateInstanceHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/instances/:id/upgrade",
					Handler: instance.UpgradeInstanceHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
