// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: network.proto

package network

import (
	"context"

	"github.com/bluven/f-cloud/app/network/rpc/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ConnectNetworkRequest    = proto.ConnectNetworkRequest
	DisconnectNetworkRequest = proto.DisconnectNetworkRequest
	Empty                    = proto.Empty

	Network interface {
		ConnectNetwork(ctx context.Context, in *ConnectNetworkRequest, opts ...grpc.CallOption) (*Empty, error)
		DisconnectNetwork(ctx context.Context, in *DisconnectNetworkRequest, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultNetwork struct {
		cli zrpc.Client
	}
)

func NewNetwork(cli zrpc.Client) Network {
	return &defaultNetwork{
		cli: cli,
	}
}

func (m *defaultNetwork) ConnectNetwork(ctx context.Context, in *ConnectNetworkRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := proto.NewNetworkClient(m.cli.Conn())
	return client.ConnectNetwork(ctx, in, opts...)
}

func (m *defaultNetwork) DisconnectNetwork(ctx context.Context, in *DisconnectNetworkRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := proto.NewNetworkClient(m.cli.Conn())
	return client.DisconnectNetwork(ctx, in, opts...)
}
