// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.0--rc1
// source: proto/storage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MountDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    uint32                 `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	DiskId        uint32                 `protobuf:"varint,2,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountDiskRequest) Reset() {
	*x = MountDiskRequest{}
	mi := &file_proto_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountDiskRequest) ProtoMessage() {}

func (x *MountDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountDiskRequest.ProtoReflect.Descriptor instead.
func (*MountDiskRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{0}
}

func (x *MountDiskRequest) GetInstanceId() uint32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *MountDiskRequest) GetDiskId() uint32 {
	if x != nil {
		return x.DiskId
	}
	return 0
}

type MountDiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountDiskResponse) Reset() {
	*x = MountDiskResponse{}
	mi := &file_proto_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountDiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountDiskResponse) ProtoMessage() {}

func (x *MountDiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountDiskResponse.ProtoReflect.Descriptor instead.
func (*MountDiskResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{1}
}

type UnmountDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskId        uint32                 `protobuf:"varint,1,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountDiskRequest) Reset() {
	*x = UnmountDiskRequest{}
	mi := &file_proto_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountDiskRequest) ProtoMessage() {}

func (x *UnmountDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountDiskRequest.ProtoReflect.Descriptor instead.
func (*UnmountDiskRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{2}
}

func (x *UnmountDiskRequest) GetDiskId() uint32 {
	if x != nil {
		return x.DiskId
	}
	return 0
}

type UnmountDiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountDiskResponse) Reset() {
	*x = UnmountDiskResponse{}
	mi := &file_proto_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountDiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountDiskResponse) ProtoMessage() {}

func (x *UnmountDiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountDiskResponse.ProtoReflect.Descriptor instead.
func (*UnmountDiskResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{3}
}

var File_proto_storage_proto protoreflect.FileDescriptor

const file_proto_storage_proto_rawDesc = "" +
	"\n" +
	"\x13proto/storage.proto\x12\astorage\"L\n" +
	"\x10MountDiskRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\rR\n" +
	"instanceId\x12\x17\n" +
	"\adisk_id\x18\x02 \x01(\rR\x06diskId\"\x13\n" +
	"\x11MountDiskResponse\"-\n" +
	"\x12UnmountDiskRequest\x12\x17\n" +
	"\adisk_id\x18\x01 \x01(\rR\x06diskId\"\x15\n" +
	"\x13UnmountDiskResponse2\x97\x01\n" +
	"\aStorage\x12B\n" +
	"\tMountDisk\x12\x19.storage.MountDiskRequest\x1a\x1a.storage.MountDiskResponse\x12H\n" +
	"\vUnmountDisk\x12\x1b.storage.UnmountDiskRequest\x1a\x1c.storage.UnmountDiskResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_storage_proto_rawDescOnce sync.Once
	file_proto_storage_proto_rawDescData []byte
)

func file_proto_storage_proto_rawDescGZIP() []byte {
	file_proto_storage_proto_rawDescOnce.Do(func() {
		file_proto_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_storage_proto_rawDesc), len(file_proto_storage_proto_rawDesc)))
	})
	return file_proto_storage_proto_rawDescData
}

var file_proto_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_storage_proto_goTypes = []any{
	(*MountDiskRequest)(nil),    // 0: storage.MountDiskRequest
	(*MountDiskResponse)(nil),   // 1: storage.MountDiskResponse
	(*UnmountDiskRequest)(nil),  // 2: storage.UnmountDiskRequest
	(*UnmountDiskResponse)(nil), // 3: storage.UnmountDiskResponse
}
var file_proto_storage_proto_depIdxs = []int32{
	0, // 0: storage.Storage.MountDisk:input_type -> storage.MountDiskRequest
	2, // 1: storage.Storage.UnmountDisk:input_type -> storage.UnmountDiskRequest
	1, // 2: storage.Storage.MountDisk:output_type -> storage.MountDiskResponse
	3, // 3: storage.Storage.UnmountDisk:output_type -> storage.UnmountDiskResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_storage_proto_init() }
func file_proto_storage_proto_init() {
	if File_proto_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_storage_proto_rawDesc), len(file_proto_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_storage_proto_goTypes,
		DependencyIndexes: file_proto_storage_proto_depIdxs,
		MessageInfos:      file_proto_storage_proto_msgTypes,
	}.Build()
	File_proto_storage_proto = out.File
	file_proto_storage_proto_goTypes = nil
	file_proto_storage_proto_depIdxs = nil
}
