// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: network.proto

package server

import (
	"context"

	"github.com/bluven/f-cloud/app/network/rpc/internal/logic"
	"github.com/bluven/f-cloud/app/network/rpc/internal/svc"
	"github.com/bluven/f-cloud/app/network/rpc/proto"
)

type NetworkServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedNetworkServer
}

func NewNetworkServer(svcCtx *svc.ServiceContext) *NetworkServer {
	return &NetworkServer{
		svcCtx: svcCtx,
	}
}

func (s *NetworkServer) ConnectNetwork(ctx context.Context, in *proto.ConnectNetworkRequest) (*proto.Empty, error) {
	l := logic.NewConnectNetworkLogic(ctx, s.svcCtx)
	return l.ConnectNetwork(in)
}

func (s *NetworkServer) DisconnectNetwork(ctx context.Context, in *proto.DisconnectNetworkRequest) (*proto.Empty, error) {
	l := logic.NewDisconnectNetworkLogic(ctx, s.svcCtx)
	return l.DisconnectNetwork(in)
}
