// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type CreateInstanceRequest struct {
	Name      string `json:"name" validate:"required"`
	CPU       uint   `json:"cpu" validate:"required,oneof=1 2 4 8 16 32"`
	Memory    uint   `json:"memory" validate:"required,oneof=4 8 16 32 64 128 256"`
	OS        string `json:"os" validate:"required,oneof=linux windows"`
	Image     string `json:"image" validate:"required"`
	NetworkID uint   `json:"networkID" validate:"required"`
	DiskID    uint   `json:"diskID" validate:"required"`
}

type DeleteRequest struct {
	ID uint `path:"id"`
}

type EmptyRequest struct {
}

type EmptyResponse struct {
}

type GetRequest struct {
	ID uint `path:"id"`
}

type Instance struct {
	ID        uint   `json:"id"`
	Name      string `json:"name"`
	UserID    uint   `json:"userID"`
	CPU       uint   `json:"cpu"`
	Memory    uint   `json:"memory"`
	OS        string `json:"os"`
	Image     string `json:"image"`
	NetworkID uint   `json:"networkID"`
	DiskID    uint   `json:"diskID"`
	Status    string `json:"status"`
}

type ListInstancesRequest struct {
	Name     string `form:"name,optional"`
	Page     uint   `form:"page,default=1" validate:"min=1"`
	PageSize uint   `form:"pageSize,default=10" validate:"oneof=10 20 30 40 50"`
}

type ListInstancesResponse struct {
	Items       []Instance `json:"items"`
	TotalRecord uint       `json:"total"`
	TotalPage   uint       `json:"totalPage"`
	Page        uint       `json:"page"`
	PageSize    uint       `json:"pageSize"`
}

type OperateInstanceRequest struct {
	ID        uint   `path:"id"`
	Operation string `path:"operation" validate:"required,oneof=start stop restart"`
}

type UpgradeInstanceRequest struct {
	ID     uint `path:"id"`
	CPU    uint `json:"cpu" validate:"required,oneof=1 2 4 8 16 32"`
	Memory uint `json:"memory" validate:"required,oneof=4 8 16 32 64 128 256"`
}
