// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: storage.proto

package server

import (
	"context"

	"github.com/bluven/f-cloud/app/storage/rpc/internal/logic"
	"github.com/bluven/f-cloud/app/storage/rpc/internal/svc"
	"github.com/bluven/f-cloud/app/storage/rpc/proto"
)

type StorageServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedStorageServer
}

func NewStorageServer(svcCtx *svc.ServiceContext) *StorageServer {
	return &StorageServer{
		svcCtx: svcCtx,
	}
}

func (s *StorageServer) MountDisk(ctx context.Context, in *proto.MountDiskRequest) (*proto.MountDiskResponse, error) {
	l := logic.NewMountDiskLogic(ctx, s.svcCtx)
	return l.MountDisk(in)
}

func (s *StorageServer) UnmountDisk(ctx context.Context, in *proto.UnmountDiskRequest) (*proto.UnmountDiskResponse, error) {
	l := logic.NewUnmountDiskLogic(ctx, s.svcCtx)
	return l.UnmountDisk(in)
}
